// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn-ZBIqoxgulnqUZfpO8tFQT28RjLbeB0',
    appId: '1:282248486695:web:c2f66d2300d16796a31302',
    messagingSenderId: '282248486695',
    projectId: 'genora-18bac',
    authDomain: 'genora-18bac.firebaseapp.com',
    storageBucket: 'genora-18bac.firebasestorage.app',
    measurementId: 'G-8M76Y4P6HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHVZiCZnroYK4n7fTbT-XlBkdcBt4j0Vs',
    appId: '1:624619623676:android:78f1280728d882f41ef379',
    messagingSenderId: '624619623676',
    projectId: 'genome-fe61e',
    storageBucket: 'genome-fe61e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASTQMlcDsxNt0tM0qMG16KFslvYbdwSO4',
    appId: '1:282248486695:ios:41b1474fbcfffa11a31302',
    messagingSenderId: '282248486695',
    projectId: 'genora-18bac',
    storageBucket: 'genora-18bac.firebasestorage.app',
    iosBundleId: 'com.example.genome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASTQMlcDsxNt0tM0qMG16KFslvYbdwSO4',
    appId: '1:282248486695:ios:41b1474fbcfffa11a31302',
    messagingSenderId: '282248486695',
    projectId: 'genora-18bac',
    storageBucket: 'genora-18bac.firebasestorage.app',
    iosBundleId: 'com.example.genome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn-ZBIqoxgulnqUZfpO8tFQT28RjLbeB0',
    appId: '1:282248486695:web:18105baca42bf131a31302',
    messagingSenderId: '282248486695',
    projectId: 'genora-18bac',
    authDomain: 'genora-18bac.firebaseapp.com',
    storageBucket: 'genora-18bac.firebasestorage.app',
    measurementId: 'G-CX66R26LE4',
  );
}
